export const foodItems = [
    {
      name: 'Veggie Delight',
      type: 'Vegetarian',
      description: 'A delicious vegetarian dish.',
      price: '9.99',
    },
    {
      name: 'Veg soup',
      type: 'Vegetarian',
      description: 'A delicious vegetarian soup.',
      price: '8.99',
    },
    {
      name: 'Veg Biriyani',
      type: 'Vegetarian',
      description: 'A delicious vegetarian Biriyani.',
      price: '14.99',
    },
    {
      name: 'Veggie Burger',
      type: 'Vegetarian',
      description: 'A delicious vegetarian Burger.',
      price: '6.99',
    },
    {
      name: 'Vegan Burger',
      type: 'Vegetarian',
      description: 'A delicious vegan Burger.',
      price: '6.99',
    },
    {
        name: 'Vegan Burger',
        type: 'Vegetarian',
        description: 'A delicious vegan Burger.',
        price: '6.99',
      },
    {
      name: 'Chicken Feast',
      type: 'Non-Vegetarian',
      description: 'A mouthwatering non-vegetarian dish.',
      price: '12.99',
    },
    {
        name: 'Chicken Burger',
        type: 'Non-Vegetarian',
        description: 'A mouthwatering non-vegetarian Biriyani.',
        price: '17.99',
      },
    {
      name: 'Chicken Biriyani',
      type: 'Non-Vegetarian',
      description: 'A mouthwatering non-vegetarian Biriyani.',
      price: '17.99',
    },
    {
      name: 'Chicken Biriyani',
      type: 'Non-Vegetarian',
      description: 'A mouthwatering non-vegetarian Biriyani.',
      price: '17.99',
    },
    {
        name: 'Chicken Burger',
        type: 'Non-Vegetarian',
        description: 'A mouthwatering non-vegetarian Biriyani.',
        price: '17.99',
      },
    {
      name: 'Chicken Burger',
      type: 'Non-Vegetarian',
      description: 'A mouthwatering non-vegetarian Biriyani.',
      price: '17.99',
    },
    {
      name: "Grandma's Special",
      type: 'Traditional',
      description: 'A traditional family recipe.',
      price: '14.99',
    },
    {
        name: "Grandma's Special",
        type: 'Traditional',
        description: 'A traditional family recipe.',
        price: '14.99',
      },
      {
        name: "Grandma's Special",
        type: 'Traditional',
        description: 'A traditional family recipe.',
        price: '14.99',
      },
    {
      name: "Grandpa's Special",
      type: 'Traditional',
      description: 'A traditional family recipe.',
      price: '14.99',
    },
    {
      name: "Grandma's Curry",
      type: 'Traditional',
      description: 'A traditional family curry recipe.',
      price: '14.99',
    },
    {
        name: "Grandma's Curry",
        type: 'Traditional',
        description: 'A traditional family curry recipe.',
        price: '14.99',
      },
  ];